# Generated by Django 5.0.6 on 2024-05-17 14:16

import core.models
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_funcionario_facebook_funcionario_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='img',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to=core.models.get_arquivo_path, variations={'thumb': {'height': 480, 'width': 480}}, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-layers', 'Design'), ('lni-cog', 'Engrenagem'), ('lni-starts-up', 'Graficos'), ('lni-users', 'Usuarios'), ('lni-mobile', 'Mobile'), ('lni-rocket', 'Foguete')], max_length=50, verbose_name='Icone'),
        ),
    ]
